name: Wakatime Statistics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Run wakatime workflow
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME }}
          GH_TOKEN: ${{ secrets.METRICS }}
          COMMIT_BY_ME: "True"
          SHOW_PROFILE_VIEWS: "False"
